### ISSUE TITLE
User registration bug with password char limit

### ISSUE THREAD

**Issue by hcaseyal** [CharlesJeremy/Schedulr#32]
The hint says that passwords must be at least 4 characters. However, when I try to register with a password less than 8 characters, I get an error message

**Comment by zhangwen0411** [comment]
Someone just change the hint; I can do it before tomorrow...  four characters is way too short...

**Comment by zhangwen0411** [comment]
Resolved by 31f434a06f16bcbefee01d8a3dfa338c07ec5c08
