### ISSUE TITLE
Bug when trying to edit (drag) bedtime shower events

### ISSUE THREAD

**Issue by hcaseyal** [CharlesJeremy/Schedulr#33]
The events are draggable, but they shouldn't be.

**Comment by zhangwen0411** [comment]
Yeah, but should they be draggable in the future?  e.g. do we want to infer users' bed times based on how they rearrange bedtime shower events?

**Comment by hcaseyal** [comment]
Sure, but in this case, dragging the event prompts an error and doesn't actually edit the event.
